name: Deploy to Firebase App Hosting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        
      - name: Clean build directories
        run: rm -rf .next out dist
        
      - name: Build for App Hosting
        run: |
          # Make CI build script executable
          chmod +x ./ci-build.sh
          # Run CI-specific build script for App Hosting
          ./ci-build.sh
          
      - name: Verify App Hosting Build
        run: |
          # Check that build directory exists for App Hosting
          if [ ! -d ".next" ]; then
            echo "❌ .next directory not found! Build failed."
            exit 1
          fi
          # Verify Next.js standalone output for App Hosting
          if [ ! -f ".next/standalone/server.js" ]; then
            echo "⚠️  Standalone server not found, but .next exists"
          fi
          echo "✅ App Hosting build verified"
          
      - name: Deploy to Firebase App Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEADFLOW }}'
          projectId: leadflow-4lvrr
          target: apphosting
          channelId: live